name: openwrt-packages-of-liuran001-auto-sync

on:
  push:
    branches:
      -master
  workflow_dispatch:
  schedule:
    - cron: 0 */24 * * *   # 每隔12小时
  watch:                                                        # 监视操作
    types: [started]                                            # 点击 Star 之后
    
env: 
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  SCKEY: ${{ secrets.SCKEY }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-20.04

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [packages]
        
    steps:
      - name: delete
        run: |
          rm -rf $GITHUB_WORKSPACE/*
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN }} # 令牌
          upstream_repository: liuran001/openwrt-packages  # 上游仓库
          target_repository: dylan8888/openwrt-packages-of-liuran001  # 你要推送的仓库
          upstream_branch: ${{matrix.target}}  # 默认是拉取上游仓库的master分支
          target_branch: ${{matrix.target}}  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
